[versions]
spring-boot = "4.0.0"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
graalvm-native = { id = "org.graalvm.buildtools.native", version = "0.11.3" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
