---
spring:
  application:
    name: Workastra Console
  main:
    banner-mode: "off"
  jmx:
    enabled: false
  mvc:
    apiversion:
      use:
        path-segment: 1
  web:
    error:
      whitelabel:
        enabled: false
